# exclude_roles:
# - ""
# - system
# - 1password
# - alacritty
# - asciiquarium
# - bash
# - bat
# - docker
# - flatpak
# - fonts
# - fzf
# - git
# - gnu-tar
# - go
# - helm
# - jq
# - k8s
# - k9s
# - lazygit
# - lua
# - nala
# - ncdu
# - neofetch
# - neovim
# - ngrok
# - npm
# - nvm
# - obsidian
# - pwsh
# - python
# - ripgrep
# - ruby
# - rust
# - ssh
# - sshfs
# - terraform
# - tig
# - tldr
# - tmate
# - tmux
# - tfenv
# - trivy
# - zellij
# - spotify
# - zoxide
