---
# - name: "tldr | Install"
#   community.general.homebrew:
#     name: tldr
#     state: present

- name: "tldr | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: tldr_distribution_config

- name: "tldr | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: tldr_distribution_config.stat.exists
