---
- name: "Lazygit | Install"
  community.general.homebrew_tap:
    name: jesseduffield/lazygit/lazygit
    state: present
# - name: Run Ubuntu Tasks
#   ansible.builtin.import_tasks: ubuntu.yml
#   when: ansible_os_family == 'Debian'
