---
- name: "checkov | Install"
  community.general.homebrew:
    name: checkov
    state: absent


# - name: "checkov | Checking for Distribution Config: {{ ansible_distribution }}"
#   ansible.builtin.stat:
#     path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
#   register: checkov_distribution_config

# - name: "checkov | Run Tasks: {{ ansible_distribution }}"
#   ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
#   when: checkov_distribution_config.stat.exists
