---
- name: "packer | Tap"
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: "packer | Install"
  community.general.homebrew:
    name: hashicorp/tap/packer
    state: present
