---
- name: "tig | Install"
  community.general.homebrew:
    name: tig
    state: present

# - name: "tig | Checking for Distribution Config: {{ ansible_distribution }}"
#   ansible.builtin.stat:
#     path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
#   register: tig_distribution_config

# - name: "tig | Run Tasks: {{ ansible_distribution }}"
#   ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
#   when: tig_distribution_config.stat.exists
