---
- name: Install ngrok
  ansible.builtin.shell:
    cmd: "curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo 'deb https://ngrok-agent.s3.amazonaws.com buster main' | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok"
    # creates: "{{ ngrok_keyring }}"
  tags:
    - ngrok

# - name: Add apt repository
#   ansible.builtin.apt_repository:
#     repo: "deb [arch={{ ngrok_arch }} signed-by={{ ngrok_keyring }}] https://ngrok-agent.s3.amazonaws.com buster main"
#     filename: ngrok
#     update_cache: True
#     state: present
#   tags:
#     - ngrok

# - name: Install required packages
#   loop:
#     - ngrok
#   ansible.builtin.package:
#     name: "{{ item }}"
#     state: present
#   tags:
#     - ngrok
