# ---

- name: "ZSH | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: zsh_distribution_config

- name: "ZSH | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  when: zsh_distribution_config.stat.exists

- name: "ZSH | Run Oh My ZSH install tasks"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/all-omz.yml"
