---
- name: "ripgrep | Install"
  community.general.homebrew:
    name: ripgrep
    state: present

# - name: "ripgrep | Checking for Distribution Config: {{ ansible_distribution }}"
#   ansible.builtin.stat:
#     path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
#   register: ripgrep_distribution_config

# - name: "ripgrep | Run Tasks: {{ ansible_distribution }}"
#   ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
#   when: ripgrep_distribution_config.stat.exists
