# ---
# - name: "thefuck | Checking for Distribution Config: {{ ansible_distribution }}"
#   ansible.builtin.stat:
#     path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
#   register: thefuck_distribution_config

# - name: "thefuck | Run Tasks: {{ ansible_distribution }}"
#   ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
#   when: thefuck_distribution_config.stat.exists

---
- name: "thefuck | {{ ansible_distribution }} | Install"
  community.general.homebrew:
    name: thefuck
    state: present
