---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run MacOS Tasks
  ansible.builtin.import_tasks: MacOSX.yml
  when: ansible_os_family == 'Darwin'
# - name: Install Packages
#   import_tasks: packages.yml
