---
- name: "GNU tar | Install"
  community.general.homebrew:
    name: gnu-tar
    state: present

# - name: "GNU tar | Checking for Distribution Config: {{ ansible_distribution }}"
#   ansible.builtin.stat:
#     path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
#   register: gnu_tar_distribution_config

# - name: "GNU tar | Run Tasks: {{ ansible_distribution }}"
#   ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
#   when: gnu_tar_distribution_config.stat.exists
