---
- name: "tofuenv | Tap"
  community.general.homebrew_tap:
    name: tofuutils/tap
    state: present


- name: "tofuenv | Install"
  community.general.homebrew:
    name: tofuenv
    state: present
