---
- name: "Neovim | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: neovim_distribution_config

- name: "Neovim | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: neovim_distribution_config.stat.exists

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files2"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
# - name: "nvim Config | Clone Latest Version"
#   ansible.builtin.git:
#     repo: https://github.com/jercle/kickstart.nvim.git
#     depth: 1
#     dest: "{{ ansible_user_dir }}/.config/nvim"
#   notify: "Clone nvim config"
