---
- name: "Ruby | Install"
  community.general.homebrew:
    name: ruby
    state: present

- name: "Ruby | Copy gemrc"
  when: envType == "ha"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/gemrc"
    dest: ~/.config/gem/gemrc
