---
- name: "Ruby | Install"
  community.general.homebrew:
    name: ruby
    state: present

- name: "Ruby | Copy gemrc"
  ansible.builtin.copy:
  when: envType == "ha"
  src: "{{ role_path }}/files/gemrc"
  dest: ~/.config/gem/gemrc
