---
- name: "Ruby | Install"
  community.general.homebrew:
    name: ruby
    state: present

- name: 'Ruby | Create ~/.config/gem dir'
  become: true
  ansible.builtin.file:
    path: ~/.config/gem
    state: directory
    mode: "0644"

- name: "Ruby | Copy gemrc"
  when: envType == "ha"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/gemrc"
    dest: ~/.config/gem/gemrc
